services:

  db:
    image: postgres:16
    container_name: theatre-db
    environment:
      POSTGRES_PASSWORD: dev
      POSTGRES_USER: dev
      POSTGRES_DB: theatre
    ports:
      - "5432:5432"
    volumes:
      - ./dev_data:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d
volumes:
  db_data:
