spring:
  application:
    name: backend

  datasource:
    url: jdbc:postgresql://localhost:5432/theatre  # Vérifiez bien que c'est la bonne BDD !
    username: dev
    password: dev
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update # Utilise 'update' pour le dev, ou 'validate' si vous préférez que Liquibase gère tout
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true

  liquibase:
    enabled: false
    change-log: classpath:db/changelog/db.changelog-master.yaml
