spring:
  application:
    name: backend

  datasource:
    url: jdbc:postgresql://localhost:5432/theatre
    username: dev
    password: dev
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true

  liquibase:
    enabled: false
    change-log: classpath:db/changelog/db.changelog-master.yaml

  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: your-super-secret-key-change-in-production

server:
  port: 8081

# URLs des microservices (informationnelles en version rapide)
payment:
  service:
    url: http://localhost:3002

auth:
  service:
    url: http://localhost:3001
